import './globals.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

import NextAuthSessionProvider from './SessionProvider';

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <NextAuthSessionProvider>
          {children}
        </NextAuthSessionProvider>
      </body>
    </html>
  );
}
